baseURL = "https://example.com"
languageCode = "en-us"
title = "Golden Blue"
theme="archie"
copyright = "© 2025 Kyle"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="light"
	useCDN=false
	mathjax = true
	subtitle = "A collection of rendering components in vdieo game development."



[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

